// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFmEqsR2iJZHVOkAlkbmUyvbIz9Z4fJrs',
    appId: '1:73472091612:web:21760c0f1f7dfc2fe6db19',
    messagingSenderId: '73472091612',
    projectId: 'flutter-chat-app-ee8e0',
    authDomain: 'flutter-chat-app-ee8e0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ee8e0.appspot.com',
    measurementId: 'G-XFZBPK3LT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADfrdm8oocg6Vb6BG1B5kmht0Dh8oCE6g',
    appId: '1:73472091612:android:fdfb4ed9d284c362e6db19',
    messagingSenderId: '73472091612',
    projectId: 'flutter-chat-app-ee8e0',
    storageBucket: 'flutter-chat-app-ee8e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonPYjmmk68sFUXmxoKcsQsj_1Z89_WpM',
    appId: '1:73472091612:ios:d4703a2cbc613270e6db19',
    messagingSenderId: '73472091612',
    projectId: 'flutter-chat-app-ee8e0',
    storageBucket: 'flutter-chat-app-ee8e0.appspot.com',
    iosClientId: '73472091612-757b6gb7ejhftnbd4g7olnfvpuspusdv.apps.googleusercontent.com',
    iosBundleId: 'vtnd.duynn.flutterChatAppDdd',
  );
}
