name: Flutter CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-channel: [ 'stable' ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies and run build runner
        run: make sync

      - name: Format code
        run: make format

      - name: Analyze
        run: make analyze

      - name: Metrics
        uses: dart-code-checker/dart-code-metrics-action@v2
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gen file google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > android/app/google-services.json

      - name: Gen file GoogleService-Info.plist
        run: echo "${{ secrets.GOOGLE_SERVICES_INFO }}" | base64 --decode > ios/GoogleService-Info.plist

      - run: echo "${{ secrets.GOOGLE_SERVICES_INFO }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Build APK
        run: flutter build apk --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.flutter-channel }}
          path: build/app/outputs/apk/release/app-release.apk